### ISSUE TITLE
CnpResponseProcessor::$deleteBatchFiles default is the quoted string "false", not an actual false value.

### ISSUE THREAD

**Issue by evanernest** [Vantiv/cnp-sdk-for-php#11]
It is later evaluated as a boolean:

```
        if(self::$deleteBatchFiles){
            if(file_exists($response_file)){
                unlink($response_file);
            }
            if(file_exists($response_file.".encrypted")){
                unlink($response_file.".encrypted");
            }
        }
```
...resulting in batch files being deleted by default.

**Comment by dissolve** [comment]
https://github.com/Vantiv/cnp-sdk-for-php/blob/64a2b36ce9d7a8ce3cce6550071057e0e6f42804/cnp/sdk/CnpResponseProcessor.php#L7


this is the offending line, it should be FALSE, not "false"

**Comment by VantivSDK** [comment]
We have fixed the issue with the latest release - https://github.com/Vantiv/cnp-sdk-for-php/releases/tag/12.17.1

**Comment by evanernest** [comment]
Thanks for the fix.
