### ISSUE TITLE
Constant given as string (again)

### ISSUE THREAD

**Issue by jdooley511** [Vantiv/cnp-sdk-for-php#12]
The fix for https://github.com/Vantiv/cnp-sdk-for-php/issues/7 appears to have been reverted for some reason.

Can the fix be put back? The argument to that function is a PHP Constant representing an integer, not a string.

**Comment by dissolve** [comment]
this is literally a one line fix, can someone fix this already?

**Comment by dissolve** [comment]
correction, it looks like this was fixed, i have another such issue to file
closing this issue

**Comment by dissolve** [comment]
oops, cannot close, @jdooley511 can you confirm its correct in the most recent version and close your issue

**Comment by jdooley511** [comment]
Yeah it looks all set.
