### ISSUE TITLE
PHP Parse error in enhancedData_multiple_lineItem.php

### ISSUE THREAD

**Issue by PayLeaseBrian** [Vantiv/cnp-sdk-for-php#2]
PHP Version: PHP 7.1.16

When running `php -l` on `enhancedData_multiple_lineItem.php` a parse error is emitted on [line 52](https://github.com/Vantiv/cnp-sdk-for-php/blob/a17f22b41dbedc3ae21ed853f38e9f934d0a5be8/cnp/sdk/Test/enhancedData_multiple_lineItem.php#L52):
```
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in enhancedData_multiple_lineItem.php on line 52

Parse error: syntax error, unexpected 'new' (T_NEW) in enhancedData_multiple_lineItem.php on line 52

Errors parsing enhancedData_multiple_lineItem.php
```

**Comment by harshitvora** [comment]
Thank you for pointing it out. It is fixed and should be working in the next release.
