### ISSUE TITLE
CNP ini config values with special characters fail silently if not quoted

### ISSUE THREAD

**Issue by kael-shipman** [Vantiv/cnp-sdk-for-php#3]
The Vantiv setup script inserts values into the ini file without quoting. If values contain special characters like `&`, the php `parse_ini_file` function silently replaces those values with `0`.

For example:

```ini
# cnp.ini
username = MyUser
password = my&password
...
```

yields the following php array:

```php
$config = parse_ini_file('my-file.ini');
print_r($config);

/** Output:
array(
    "username" => "MyUser",
    "password" => "0"
)
*/
```

This happened to us when Vantiv gave us a production password with an ampersand (`&`) in it. Everything worked in the test environment, but when we switched to production, everything was failing with a "System Error - Call Vantiv" error message. This was because the config was writing our password as `0`, rather than the password with the `&` sign in it that vantiv had given us.

While it was sufficient to simply quote the password value in the ini file, we had Vantiv change our password to something without an `&` in it.

Still, though, this should NOT fail silently. It caused an error in our production environment that lost us clients.

**Comment by harshitvora** [comment]
Thank you for pointing out the issue. It is fixed and will be available in the next release.
