### ISSUE TITLE
PHP 8 warning in CnpXmlMapper.php

### ISSUE THREAD

**Issue by mteall** [Vantiv/cnp-sdk-for-php#37]
Starting in PHP 8, a warning is emitted when a required method parameter follows an optional method parameter.  In running some unit testing, I found that this situation exists in the CnpXmlMapper::request method.  

Suggested change:

public function request($request,$hash_config=NULL,$useSimpleXml)

to

public function request($request,$hash_config=NULL,$useSimpleXml=FALSE)

I opened a pull request, but could not add any reviewers: https://github.com/Vantiv/cnp-sdk-for-php/pull/34

**Comment by ls-tyler-roach** [comment]
Are there plans to fix this bug and merge this PR? This is causing a deprecation error with PHP 8.1

**Comment by mteall** [comment]
I would love that.  I am currently maintaining a separate, forked
repository with JUST my one change at my company.  I got a reply from
Vantiv months ago saying they would merge my PR.  Multiple releases have
gone out, my PR is still just there.

On Thu, Nov 30, 2023 at 10:40 AM Tyler Roach ***@***.***>
wrote:

> Are there plans to fix this bug and merge this PR? This is causing a
> deprecation error with PHP 8.1
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Vantiv_cnp-2Dsdk-2Dfor-2Dphp_issues_37-23issuecomment-2D1834353829&d=DwMFaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=l9bmBOYTAR4zvF1sljGIZ1NQy-UDCDFEJkn6p_d370E&m=iCC0BgnDmdWvipTZKUepA5do695ixNStaBZQodA5-mE1InzzNd6vq4df86NA-M_4&s=LYm64Hn2sjzyQwXlUp8oNb1xingqM2hhU_amcw2zoPI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APITMXGRMAUBAWKYKQNJU4DYHDHLJAVCNFSM6AAAAAAQYHX5W6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZUGM2TGOBSHE&d=DwMFaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=l9bmBOYTAR4zvF1sljGIZ1NQy-UDCDFEJkn6p_d370E&m=iCC0BgnDmdWvipTZKUepA5do695ixNStaBZQodA5-mE1InzzNd6vq4df86NA-M_4&s=jRepqxeIbBP_7jAiT2OV673YFGqAqnxUUUzdhTtrlrc&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

Respectfully,

*Mike Teall*

Software Engineer III

PayLease

P | 858.260.5108

E | ***@***.***

www.paylease.com

<https://www.facebook.com/PayLease>
<http://www.linkedin.com/company/paylease-llc>
<https://twitter.com/paylease>
<https://plus.google.com/+PayLeaseSanDiego/posts>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.
