### ISSUE TITLE
Debugging print statement returned

### ISSUE THREAD

**Issue by TheOtherBrianJ** [Vantiv/cnp-sdk-for-php#6]
It appears a debugging print statement has returned. I haven't had time to review code looking for others yet.

https://github.com/Vantiv/cnp-sdk-for-php/blob/8a4b27bffa620abad91e726b922b822651afafbf/cnp/sdk/CnpOnlineRequest.php#L1253

**Comment by swapnilhande** [comment]
@jrhill95 fixed it and should be all set with 12.7.1 release
